### ISSUE TITLE
Psycopg3 ProactorEventLoop compatibility on Windows

### ISSUE THREAD

**Issue by xauuu** [langflow-ai/langflow#10363]
### Bug Description

Langflow fails to start on Windows when using PostgreSQL with Psycopg3 driver due to incompatible event loop policy.
```
psycopg.InterfaceError: Psycopg cannot use the 'ProactorEventLoop' to run in async mode. 
Please use a compatible event loop, for instance by setting 
'asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())'
```

### Reproduction

1. uv pip install langflow
2. LANGFLOW_DATABASE_URL="postgresql://user:password@localhost:5432/dbname"
3. uv run langflow run --env-file .env

### Expected behavior

- Langflow should start successfully on Windows with PostgreSQL  
- Database tables should be created without errors  

### Who can help?

@italojohnny 

### Operating System

Windows

### Langflow Version

1.6.5

### Python Version

3.10

**Comment by Empreiteiro** [comment]
@xauuu Already fixed in main: https://github.com/langflow-ai/langflow/pull/9899.

**Comment by xauuu** [comment]
Thanks @Empreiteiro ! So we just need to wait for the next release that includes the fix from #9899, right?

**Comment by xauuu** [comment]
Hi @italojohnny , @Empreiteiro 

I tried installing langflow-nightly but still got the same error
```
1. conda activate py310
2. uv venv langflow-env
3. langflow-env\Scripts\activate
4. uv pip install langflow-nightly
5. uv pip install "psycopg[binary,pool]"
6. langflow --version
   langflow 1.6.5.dev1
7. uv run langflow run --env-file .env
```

.env file:
```
LANGFLOW_DATABASE_URL=postgresql+psycopg://postgres:123456@localhost:5432/langflow_db
LANGFLOW_AUTO_LOGIN=False
LANGFLOW_DEBUG_LEVEL=debug
LANGFLOW_SUPERUSER=admin
LANGFLOW_SUPERUSER_PASSWORD=admin123
```


If create file `start.py` and run cmd `python start.py`:
```
import asyncio
import platform
import uvicorn

if platform.system() == "Windows":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

if __name__ == "__main__":
    uvicorn.run("langflow.main:create_app", factory=True, host="0.0.0.0", port=7860, reload=True, log_level="debug", loop="asyncio", env_file=".env")
```
But that only starts the backend and migration successfully — frontend is not served.

**Comment by Empreiteiro** [comment]
@xauuu You can clone main. The nightly build has been experiencing issues for the past few days. Once the nightly build is aligned with the current main build, it may also be an option.

**Comment by xauuu** [comment]
@Empreiteiro Hi, I tried running Langflow using the latest code from the `main` branch as suggested, but I'm still encountering the same issue on Windows with Psycopg3 and the event loop.

https://github.com/user-attachments/assets/f4ac916a-9634-41a3-bb47-9d6723a87f64
