### ISSUE TITLE
Flow does not transfer dictionary to MCP tool

### ISSUE THREAD

**Issue by drfenixion** [langflow-ai/langflow#9881]
### Bug Description

Model generate input for MCP tool like: `"{'msg': {'linear': {'x': 1}}, 'msg_type': 'geometry_msgs/msg/Twist', 'topic': '/turtle1/cmd_vel'}"`
MCP tool get: `"{'msg': {}, 'msg_type': 'geometry_msgs/msg/Twist', 'topic': '/turtle1/cmd_vel'}"`

### Reproduction

1. Install Ollama
2. ollama run qwen3:4b

3. Install ROS2 Jazzy (https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debs.html#)
4. `sudo apt install ros-${ROS_DISTRO}-rosbridge-server`
6. `source /opt/ros/jazzy/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml`
7. Open new terminal
8. `source /opt/ros/jazzy/setup.bash && ros2 run turtlesim turtlesim_node`
7. Open new terminal
9. `source /opt/ros/jazzy/setup.bash && uv run langflow run`
10. Install flow to Langflow [ROS2 tools calling (3).json](https://github.com/user-attachments/files/22353235/ROS2.tools.calling.3.json)
11. install ros-mcp-server (https://github.com/robotmcp/ros-mcp-server/blob/main/docs/installation.md)
12. Recreate MCP server block in Langflow based on path in your system to ros-mcp-server repo (see ros-mcp-server installation).

1. Fix link from Agent response to Chat input (there is bug that broke link every time)
2. Run flow 

Model will generate instruction for moving robot. Somewere in Langflow dict part of inputs to MCP tool will be cuted and robot can not be moved. I tested it with debugger in Langflow and ros-mcp-server but cant find place in Langeflow where dictionary part of payload is cuted.

You can use any other MCP tool with dictionary payload for test. 

### Expected behavior

Model generate input for MCP tool like: `"{'msg': {'linear': {'x': 1}}, 'msg_type': 'geometry_msgs/msg/Twist', 'topic': '/turtle1/cmd_vel'}"`
MCP tool should get: `"{'msg': {'msg': {'linear': {'x': 1}}, 'msg_type': 'geometry_msgs/msg/Twist', 'topic': '/turtle1/cmd_vel'}"`

### Operating System

Ubuntu 24.04

### Langflow Version

1.5.1

### Python Version

3.11

### Flow File

[ROS2 tools calling (3).json](https://github.com/user-attachments/files/22353381/ROS2.tools.calling.3.json)

**Comment by drfenixion** [comment]
Found the place where is dict payload is cuted.

langflow/lib/python3.11/site-packages/langchain_core/tools/base.py
```
                result = input_args.model_validate(tool_input)
                result_dict = result.model_dump()
```

**Comment by drfenixion** [comment]
Debugger screenshoot with place of dictionary cuting of playload.
```
                result = input_args.model_validate(tool_input)
                result_dict = result.model_dump()
```
<img width="2554" height="1414" alt="Image" src="https://github.com/user-attachments/assets/a0417262-abe0-4908-8ffd-be53769d50e7" />

**Comment by drfenixion** [comment]
Debugger screenshoot with second place of dictionary cuting of playload. 
`validated = arg_schema.model_validate(provided_args)`

<img width="2560" height="1413" alt="Image" src="https://github.com/user-attachments/assets/533f7a21-3b25-42a2-be42-c5d9a3ff4fc5" />

**Comment by drfenixion** [comment]
Disabling that strings and send vars directly leads to fix issue. 

```
                result = input_args.model_validate(tool_input)
                result_dict = result.model_dump()

                validated = arg_schema.model_validate(provided_args)
```


I belive it should be fixed by tuning validation and not by disabling it. I let it do for maintainers.

**Comment by drfenixion** [comment]
@Empreiteiro 
Any chance to fix that bug in next release?

I want to integrate Langflow to RobotCAD pipeline and it blockes.

**Comment by Empreiteiro** [comment]
I forward the issue to the technical team for evaluation.

**Comment by stefan-sigle** [comment]
It looks like in release 1.8.0 this issue persists. Hopefully this gets addressed soon since it is a pretty big impairment for the use of mcp tools with langflow. I think this could related or even be the same issue as https://github.com/langflow-ai/langflow/issues/10975

**Comment by Empreiteiro** [comment]
@stefan-sigle We've gathered this and other issues related to MCP to refactor the feature.

We'll have the fix soon.

**Comment by Cristhianzl** [comment]
hi @stefan-sigle.
Thanks for your report.
Please follow up the PR #12601 with the fix.

Cya!
